services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    develop:
      watch:
        - action: sync+restart
          path: ./
          target: /app
          ignore:
            - ./testdata

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8888:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@database:27017/
      ME_CONFIG_BASICAUTH: false
